const constants = {
	REGISTER_ACTIVE: "REGISTER_ACTIVE",
	REGISTER_TEAM: "REGISTER_TEAM",
	REGISTER_STATUS: {
		NOT_YET: "NOT_YET",
		IN_PROCESS: "IN_PROCESS",
		DONE: "DONE"
	},
	REGISTER_FORM: {
		EDIT_TEAM_NAME: "EDIT_TEAM_NAME",
		EDIT_EMAIL: "EDIT_EMAIL",
		EDIT_NAME: "EDIT_NAME",
		EDIT_PHONE: "EDIT_PHONE",
		EDIT_UNIVERCITY: "EDIT_UNIVERCITY",
		EDIT_SKILLS: "EDIT_SKILLS",
		EDIT_EXTRA_SKILLS: "EDIT_EXTRA_SKILLS",
		EDIT_ASVICE: "EDIT_ASVICE"
	}
};

export default constants;
